In [17]:
# import dependencies

import pandas as pd
import hvplot.pandas
import matplotlib.pyplot as plt
import os
from pathlib import Path
import csv

In [23]:
# Read the census data into a Pandas DataFrame
file_path = Path("Data/Oakville_2021.csv")
data = pd.read_csv(file_path, encoding="ISO-8859-1", low_memory=True)
#data = pd.read_csv(file_path, encoding="UTF-8", index_col="year")
data

,Topic,Characteristic,Total,Total_Flag,Men+,Men+_Flag,Women+,Women+_Flag,Total.1,Total_Flag.1,Men+.1,Men+_Flag.1,Women+.1,Women+_Flag.1
0,Population and dwellings,"Population, 2021",213759.0,NaN,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
1,Population and dwellings,"Population, 2016",193832.0,NaN,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
2,Population and dwellings,"Population percentage change, 2016 to 2021",10.3,NaN,NaN,...,NaN,...,10.3,NaN,NaN,...,NaN,...
3,Population and dwellings,Total private dwellings,76179.0,NaN,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
4,Population and dwellings,Private dwellings occupied by usual residents,73558.0,NaN,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2626,Eligibility and instruction in the minority of...,Total - Eligibility and instruction in the min...,39840.0,NaN,20290.0,NaN,19550.0,NaN,100.0,NaN,100.0,NaN,100.0,NaN
2627,Eligibility and instruction in the minority of...,Children eligible for instruction in the min...,3965.0,NaN,1980.0,NaN,1990.0,NaN,10.0,NaN,9.8,NaN,10.2,NaN
2628,Eligibility and instruction in the minority of...,Eligible children who have been instructed...,2305.0,NaN,1140.0,NaN,1165.0,NaN,5.8,NaN,5.6,NaN,6.0,NaN
2629,Eligibility and instruction in the minority of...,Eligible children who have not been instru...,1665.0,NaN,840.0,NaN,825.0,NaN,4.2,NaN,4.1,NaN,4.2,NaN
2630,Eligibility and instruction in the minority of...,Children not eligible for instruction in the...,35875.0,NaN,18320.0,NaN,17560.0,NaN,90.0,NaN,90.3,NaN,89.8,NaN